type NetflixContent = {
    title: string,
    id: number,
    description: string,
    show_id: number,
    type: string,
    director: string,
    cast: string,
    country: string,
    release_year: number,
    rating: string,
    runtime: number,
    time_denomination: string,
    listed_in: string,
    year_added: number,
    month_added: string,
    day_added: string,
    created_at: Date,
    updated_at: Date,
    };